### PR TITLE
Fix log print error 

### PR DESCRIPTION
**Pull request by winrouter**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix log print error and modify the name of value in pluginslist.go
2. import coding 

**Which issue(s) this PR fixes**:

Fixes # NONE 

**Special notes for your reviewer**:

@stoneshi-yunify @pixiake 

 help me check the modify, thanks

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by stoneshi-yunify — COMMENTED** [review]
/lgtm

**Comment by winrouter** [comment]
/cc @pixiake  
help me review the modify, thanks

**Pull request merged**
