### PR TITLE
add audit percent

### PR DESCRIPTION
**Pull request by iNineku**

### CODE REVIEW

**Comment by ruiyaoOps** [comment]
@iNineku 
Can you explain how the display looks like ?
Do you know what AuditPeriod does? if you don't know, please restore it.
Why use tab to replace spaces？

**Comment by ruiyaoOps** [comment]
I think the result is only 0 and 100 in CR, right ?

**Comment by iNineku** [comment]
> @iNineku Can you explain how the display looks like ? Do you know what AuditPeriod does? if you don't know, please restore it. Why use tab to replace spaces？

@ruiyaoOps 
AuditPercent is similar to AuditResult, the difference is that that it will change with the progress of audit.
I think auditperiod is interval of regular patrol inspection.
I used go fmt.
No, its value ranges from 0 to 100, not just 0 and 100.

**Pull request merged**
