### PR TITLE
Using a much faster go proxy server

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Test results from goproxy.io
```
➜  kubeye git:(change-goproxy) ✗ ping goproxy.io -c 3
PING goproxy.io (119.28.201.50): 56 data bytes
64 bytes from 119.28.201.50: icmp_seq=0 ttl=44 time=105.338 ms
64 bytes from 119.28.201.50: icmp_seq=1 ttl=44 time=154.306 ms
64 bytes from 119.28.201.50: icmp_seq=2 ttl=44 time=279.585 ms

--- goproxy.io ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 105.338/179.743/279.585/73.375 ms
```

Test results from proxy.golang.org
```
➜  kubeye git:(change-goproxy) ✗ ping -c 3 proxy.golang.org
PING proxy.golang.org (172.217.160.81): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1

--- proxy.golang.org ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
```

As we can see from above, goproxy.io is much faster than another one. Also, you can get more details from the [website](https://goproxy.io/).

/kind cleanup

### CODE REVIEW

**Review by Forest-L — COMMENTED** [review]
Not kubekey, is kubeeye.

**Review by Forest-L — COMMENTED** [review]
The OWNERS file already exists in the root directory.

**Comment by LinuxSuRen** [comment]
> The OWNERS file already exists in the root directory.

We can put the file in different places. So we can control it according to different directories or area.

**Comment by LinuxSuRen** [comment]
> Not kubekey, is kubeeye.

fixed

**Review by Forest-L — COMMENTED** [review]
There is no master branch at present. Use the main branch.

**Review by Forest-L — COMMENTED** [review]
The project must be released using the Packr tool.

**Comment by LinuxSuRen** [comment]
> The project must be released using the Packr tool.

fixing it in #53

**Comment by LinuxSuRen** [comment]
> The project must be released using the Packr tool.

I see. The release drafter is not in conflict with the Packr tool.

**Comment by Forest-L** [comment]
Other tool distribution packages have problems, possibly with the code structure.

**Comment by LinuxSuRen** [comment]
> Other tool distribution packages have problems, possibly with the code structure.
> The problem is that the embedded rules cannot be found

I don't quite understand the problem that you're describing. Perhaps we can discuss it in the GitHub discussion if you think it's ok.

**Comment by Forest-L** [comment]
It doesn't matter, you can provide the way to release an installation package test, to see if there is no problem.

**Pull request merged**
