### PR TITLE
Import all auth plugins

### PR DESCRIPTION
**Pull request by RealHarshThakur**
Signed-off-by: Harsh Thakur <harshthakur9030@gmail.com>

Fixes https://github.com/kubesphere/kubeeye/issues/61

### CODE REVIEW

**Comment by ruiyaoOps** [comment]
@RealHarshThakur  I had a test on GCP, it can't work on it, so what fixed by this PR?

**Comment by ruiyaoOps** [comment]
kubeeye is working well at AKS and EKS, there are no problems.

**Comment by RealHarshThakur** [comment]
@ruiyaoOps I tested with GKE itself and it worked for me. Can you please try again?

**Comment by ruiyaoOps** [comment]
image

**Comment by ruiyaoOps** [comment]
image

**Comment by ruiyaoOps** [comment]
image

it works @pixiake pi

thanks for your contribution @RealHarshThakur

**Comment by pixiake** [comment]
@all-contributors please add @RealHarshThakur for code

**Pull request merged**
