### PR TITLE
add the audit results level

### PR DESCRIPTION
**Pull request by ruiyaoOps**
### What type of PR is this?
/kind feature

###  What this PR does / why we need it:
add the audit results level, for calculation the cluster scores, each result in CRD status has a level.

### Which issue(s) this PR fixes:
https://github.com/kubesphere/kubeeye/issues/140

Signed-off-by: yaorui <yaorui@yunify.com>

### CODE REVIEW

**Comment by zheng1** [comment]
Is it necessary to set normal for items that have been checked and passed?

**Comment by ruiyaoOps** [comment]
> Is it necessary to set normal for items that have been checked and passed?

The check passed item will not be displayed in the results. because if the display in the results, the output of the command-line will be very long, which is not friendly to users of command-line tools.

**Pull request merged**
